name: Try
on: [push, pull_request]

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Get gcovr
        run: sudo apt-get install gcovr

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Generate build environment
        run: cmake -G Ninja -B bin

      - name: Build
        run: ninja -C bin

      - name: Unit test
        run: ./bin/Try_test && gcovr --root . --exclude googletest --exclude test

      - name: Run demo
        run: ./bin/Try
