name: Try
on: [push, pull_request]

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest CMake and Ninja
        # Using 'latest' branch, the most recent CMake and ninja are installed.
        uses: lukka/get-cmake@latest

      - name: Run CMake
        run: pwd && ls -al && cmake -G Ninja -B bin

      - name: Run Ninja
        run: ninja -C bin

      - name: Run Try demo
        run: ./bin/Try
